[env]
DEEPGRAM_API_KEY = "52e9b46a41b1ad532b414ef646b4ccf69d20e5e7"
CEREBRAS_API_KEY = "csk-2xwdfepcey4932jdc9eer5mr353kkvjfkymvx53v6hkyxk3y"
OPENAI_API_KEY = "{{ env.CEREBRAS_API_KEY }}"
OPENAI_API_BASE = "https://api.cerebras.ai/v1/"
OPENAI_MODEL = "qwen-3-32b"

CIVICSIGNAL_LOG_LEVEL = "DEBUG"


[tasks.funnel-ts]
description = "Serve the UI over the internet via tailscale"
env = { PORT = "8080" }
dir = "{{ config_root }}"
run = "sudo tailscale funnel --bg $PORT && marimo run civicsignal/app.py --port $PORT; sudo tailscale funnel reset"

[tasks.serve-ts]
description = "Serve the UI over tailnet"
env = { PORT = "8080", HOST = "claynix.squirrel-tailor.ts.net" }
dir = "{{ config_root }}"
run = "sudo tailscale serve --bg $PORT && marimo run civicsignal/app.py --port $PORT; sudo tailscale serve reset"