[project]
name = "civicsignal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "chromadb>=1.0.15",
    "openai>=1.98.0",
    "sentence-transformers>=5.0.0",
    "transformers>=4.54.1",
]
